/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SupplierSynergy;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JScrollBar;

/**
 *
 * @author shadman
 */
public class Orders extends javax.swing.JPanel {

    /**
     * Creates new form ManageBooksPanel
     */
    public Orders() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new lib.JSqlTablel1();
        txt_serach = new javax.swing.JTextField();
        btn_search = new necesario.RSMaterialButtonCircle();
        jPanel1 = new javax.swing.JPanel();
        btn_remove = new javax.swing.JButton();
        btn_add1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Glass Antiqua", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(251, 51, 51));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Book_50px_1.png"))); // NOI18N
        jLabel11.setText("Orders");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 210, 90));

        tbl.setLIMIT(100);
        tbl.setSQLQuery("SELECT order_id, Product.name AS Item, Retailer.name AS Client, order_time, quantity, status FROM Orders INNER JOIN Product on Product.product_id = Orders.product_id INNER JOIN Retailer on Retailer.retailer_id = Orders.retailer_id ORDER BY order_id");
        jScrollPane1.setViewportView(tbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1200, 560));

        txt_serach.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 251)));
        txt_serach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_serachActionPerformed(evt);
            }
        });
        add(txt_serach, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 250, 40));

        btn_search.setText("Serach");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 50, 120, 50));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_remove.setBackground(new java.awt.Color(255, 51, 51));
        btn_remove.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        btn_remove.setForeground(new java.awt.Color(255, 255, 255));
        btn_remove.setText("Remove");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 30, -1, 30));

        btn_add1.setBackground(new java.awt.Color(102, 204, 0));
        btn_add1.setFont(new java.awt.Font("Glass Antiqua", 0, 18)); // NOI18N
        btn_add1.setForeground(new java.awt.Color(255, 255, 255));
        btn_add1.setText("Add");
        btn_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, -1, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1200, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_serachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_serachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_serachActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        String query = txt_serach.getText();
        tbl.setSQLWhere("Item LIKE \"%"+query+"%\"");
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        // TODO add your handling code here:
        int[] rows = tbl.getSelectedRows();
        Vector<String> ids = new Vector<>();
        DefaultTableModel model = (DefaultTableModel)tbl.getModel();
        for (int i=0; i < rows.length; i++) ids.add(model.getValueAt(rows[i], 0).toString());
        for (String id: ids) {
            try {
                Connection con = DBConnection.getConnection();
                String query_insert = "DELETE FROM Product WHERE supplier_id = ?";
                PreparedStatement par = con.prepareStatement(query_insert);
                par.setInt(1, Integer.valueOf(id));
                par.executeUpdate();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        tbl.load_data();
    }//GEN-LAST:event_btn_removeActionPerformed

    private void btn_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add1ActionPerformed
        // TODO add your handling code here:
        new SupplierSynergy.AddItems.AddOrder().setVisible(true);
    }//GEN-LAST:event_btn_add1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add1;
    private javax.swing.JButton btn_remove;
    private necesario.RSMaterialButtonCircle btn_search;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private lib.JSqlTablel1 tbl;
    private javax.swing.JTextField txt_serach;
    // End of variables declaration//GEN-END:variables
}
