/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SypplierSynergy;

/**
 *
 * @author shadman
 */
public class CustomQuery extends javax.swing.JPanel {

    /**
     * Creates new form ManageBooksPanel
     */
    public CustomQuery() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_query = new javax.swing.JTextField();
        rSMaterialButtonCircle1 = new necesario.RSMaterialButtonCircle();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new lib.JSqlTablel1();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Glass Antiqua", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(251, 51, 51));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Book_50px_1.png"))); // NOI18N
        jLabel11.setText("Custom Query");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 370, 80));

        jLabel1.setFont(new java.awt.Font("Glass Antiqua", 0, 28)); // NOI18N
        jLabel1.setText("SQL Query :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 140, 30));

        txt_query.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 251)));
        add(txt_query, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 880, 40));

        rSMaterialButtonCircle1.setText("Go");
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });
        add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 110, 120, 50));

        jScrollPane1.setBorder(null);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1200, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
        // TODO add your handling code here:
        String query = txt_query.getText();
        tbl.setSQLQuery(query);
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane1;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private lib.JSqlTablel1 tbl;
    private javax.swing.JTextField txt_query;
    // End of variables declaration//GEN-END:variables
}
