/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SypplierSynergy;

/**
 *
 * @author shadman
 */
public class Products extends javax.swing.JPanel {

    /**
     * Creates new form ManageBooksPanel
     */
    public Products() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_suppliers = new lib.JSqlTablel1();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Glass Antiqua", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(251, 51, 51));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Book_50px_1.png"))); // NOI18N
        jLabel11.setText("Products");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 190, 90));

        tbl_suppliers.setLIMIT(100);
        tbl_suppliers.setSQLQuery("SELECT Product.product_id, Product.name AS name, description, unit_price AS price, Supplier.name AS Supplier FROM Product INNER JOIN Supplier_Product ON Supplier_Product.product_id = Product.product_id INNER JOIN Supplier ON Supplier_Product.supplier_id = Supplier.supplier_id ORDER BY product_id ASC");
        jScrollPane1.setViewportView(tbl_suppliers);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1200, 650));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane1;
    private lib.JSqlTablel1 tbl_suppliers;
    // End of variables declaration//GEN-END:variables
}
